CREATE TABLE `article_product_promo_info_vendor_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `product_id` bigint(20) NOT NULL,
  `task_id` bigint(20) DEFAULT NULL,
  `title_en` varchar(255) DEFAULT NULL,
  `title_ch` varchar(255) DEFAULT NULL,
  `desc_en` varchar(4096) DEFAULT NULL,
  `desc_ch` varchar(4096) DEFAULT NULL,
  `share_title_en` varchar(255) DEFAULT NULL,
  `share_title_ch` varchar(255) DEFAULT NULL,
  `share_desc_en` varchar(255) DEFAULT NULL,
  `share_desc_ch` varchar(255) DEFAULT NULL,
  `img_url` varchar(255) DEFAULT NULL,
  `card_width` smallint(4) DEFAULT NULL,
  `card_height` smallint(4) DEFAULT NULL,
  `price` varchar(15) DEFAULT NULL,
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `author_id` bigint(20) DEFAULT NULL,
  `keywords` varchar(255) DEFAULT NULL,
  `missed_time` datetime DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `confirmed_time` datetime DEFAULT NULL,
  `confirmer_id` bigint(20) DEFAULT NULL,
  `status` int(1) DEFAULT '0',
  `promo_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;